#!/bin/bash
#
# Create static sites with Initializr
# https://github.com/verekia/initializr

set -e

initializr () {
  set_default_modules
  process_options $@

  if [[ $# > 0 ]]; then
    create_project
    remove_the_initializr_folder
    display_result
  else
    display_usage
    exit 1
  fi
}

process_options () {
  while getopts ":h-:" opt; do
    case "$opt" in
      -)
        case "${OPTARG}" in
          help)
            display_usage
            exit 0
            ;;
          bootstrap)
            remove_module modernizr
            add_module boot-css
            add_module boot-hero
            add_module boot-scripts
            add_module modernizrrespond
            ;;
          h5bp)
            add_module h5bp-content
            add_module h5bp-404
            add_module h5bp-adobecrossdomain
            add_module h5bp-css
            add_module h5bp-htaccess
            add_module h5bp-humans
            add_module h5bp-robots
            add_module h5bp-scripts
            ;;
          responsive)
            remove_module modernizr
            add_module izr-responsive
            add_module modernizrrespond
            ;;
          *)
            echo "Invalid option --${OPTARG}" >&2
            display_usage
            exit 1
            ;;
        esac;;
      h)
        display_usage
        exit 0
        ;;
      \?)
        echo "Invalid option: -$OPTARG" >&2
        display_usage
        exit 1
        ;;
    esac
  done
  project_folder="$BASH_ARGV"
}

add_module () {
  modules+=($1)
}

remove_module () {
  modules=(${modules[@]//$1/})
}

set_default_modules () {
  modules=(
    jquerymin
    modernizr
    h5bp-iecond
    h5bp-chromeframe
    h5bp-analytics
    h5bp-favicon
    h5bp-appletouchicons
  )
}

builder_url () {
  local query_string=$(printf "&%s" "${modules[@]}")
  query_string=${query_string:1}
  echo "http://www.initializr.com/builder?${query_string}"
}

create_project () {
  echo "Creating initializr site in '$project_folder'"
  mkdir -p $project_folder
  tar -zxf <(curl $(builder_url)) -C $project_folder
}

remove_the_initializr_folder () {
  rsync -a "$project_folder/initializr/" $project_folder
  rm -Rf "$project_folder/initializr"
}

display_result () {
  cat <<ResultMessage

  Created initializr site in '$project_folder'
ResultMessage
}

display_usage () {
  cat <<UsageMessage
  Create a new static site with Initializr
  https://github.com/verekia/initializr

  Usage: $(basename $0) [options] <site-name>

  Options:
    --bootstrap   Bootstrap template
    --h5bp        HTML5 Boilerplate template
    --responsive  Responsive template

    -h, --help    Display this message

UsageMessage
}

initializr $@
