#!/bin/bash
#
# Create static sites with Initializr
# https://github.com/verekia/initializr

initializr () {
  while getopts ":h" opt; do
    case $opt in
      h)
        display_usage
        exit 0
        ;;
      \?)
        echo "Invalid option: -$OPTARG" >&2
        display_usage
        exit 1
        ;;
    esac
  done

  if [[ $# > 0 ]]; then
    create_project "$1"
    remove_the_initializr_folder "$1"
    echo
    echo "Created initializr site in '$1'"
  else
    display_usage
    exit 1
  fi
}

create_project () {
  mkdir -p "$1"
  tar -zxf <(curl http://www.initializr.com/builder) -C "$1"
}

remove_the_initializr_folder () {
  rsync -a "$1/initializr/" "$1"
  rm -Rf "$1/initializr"
}

display_usage () {
  cat <<UsageMessage
  usage: $(basename $0) <site-name>

  Create a new static site with Initializr
  https://github.com/verekia/initializr
UsageMessage
}

initializr $@
