#!/bin/bash
#
# Create static sites with Initializr
# https://github.com/verekia/initializr

set -e

initializr () {
  modules=(jquerymin modernizr)
  process_options $@

  if [[ $# > 0 ]]; then
    create_project
    remove_the_initializr_folder
    echo
    echo "Created initializr site in '$1'"
  else
    display_usage
    exit 1
  fi
}

process_options () {
  while getopts ":h-:" opt; do
    case "$opt" in
      -)
        case "${OPTARG}" in
          help)
            display_usage
            exit 0
            ;;
          *)
            echo "Invalid option --${OPTARG}" >&2
            display_usage
            exit 1
            ;;
        esac;;
      h)
        display_usage
        exit 0
        ;;
      \?)
        echo "Invalid option: -$OPTARG" >&2
        display_usage
        exit 1
        ;;
    esac
  done
  project_folder="$BASH_ARGV"
}

builder_url () {
  query_string=$(printf "&%s" "${modules[@]}")
  query_string=${query_string:1}
  echo "http://www.initializr.com/builder?${query_string}"
}

create_project () {
  echo "Creating initializr site in '$project_folder'"
  mkdir -p $project_folder
  tar -zxf <(curl $(builder_url)) -C $project_folder
}

remove_the_initializr_folder () {
  rsync -a "$project_folder/initializr/" $project_folder
  rm -Rf "$project_folder/initializr"
}

display_usage () {
  cat <<UsageMessage
  usage: $(basename $0) <site-name>

  Create a new static site with Initializr
  https://github.com/verekia/initializr
UsageMessage
}

initializr $@
